import type { Metadata } from "next";
import "./globals.css";
import styles from "../components/layout.module.css"
import Common from "@/components/layout/common";
import { ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
};

export const metadata: Metadata = {
  title: "oshimmmm portfolio",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <html lang="ja">
      <body
        className={styles.container}
      >
        <Common />
        {children}
      </body>
    </html>
  );
};

export default Layout;